# core/board.py
from typing import Protocol, Optional, Tuple, List

Color = Tuple[int,int,int]

class BoardProtocol(Protocol):
    cols: int
    rows: int
    def inside(self, x: int, y: int) -> bool: ...
    def empty_at(self, x: int, y: int) -> bool: ...
    def valid(self, piece) -> bool: ...
    def lock(self, piece) -> int: ...  # returns cleared lines
    def clear_lines(self) -> int: ...
    def drop_distance(self, piece) -> int: ...
