# core/rules.py
from typing import Protocol, Iterable, Tuple, Optional

class RuleSet(Protocol):
    def score(self, cleared_lines: int, level: int) -> int: ...
    def fall_interval_ms(self, level: int) -> int: ...
    def lock_delay_ms(self, level: int) -> int: ...
    def kick_table(self, kind: str, from_rot: int, to_rot: int) -> Iterable[int]: ...
