# render/painters.py
class BoardPainter:
    def __init__(self, theme: Theme, cell: int): ...
    def draw(self, screen, board: BoardProtocol): ...

class PiecePainter:
    def __init__(self, theme: Theme, cell: int): ...
    def draw_current(self, screen, piece): ...
    def draw_ghost(self, screen, piece, board: BoardProtocol): ...

class HudPainter:
    def __init__(self, theme: Theme): ...
    def draw(self, screen, score:int, level:int, lines:int, paused:bool, over:bool): ...
